### ISSUE TITLE
Constantly getting ‘armed’ status for individual cameras

### ISSUE THREAD

**Issue by lovie** [bartdorsey/homebridge-blinkcameras#19]
Even if one of the individual cameras is disarmed, on the next refresh the status comes back as armed.

**Comment by bartdorsey** [comment]
Yep, I'm seeing this too, not sure what's causing it, I'm going to have to insert more logging to see if I can determine the cause.

**Comment by bartdorsey** [comment]
So turns out the node-blink-security module has two properties "armed" and "enabled". "armed" just reflects the status of the network (the blink module) it is part of, while "enabled" reflects if motion is enabled or not. So in 1.0.3 I'm changing it to use 'enabled'.  In a future version I may change it so it pays attention to both. This way if you turn off the System, the cameras associated also show up as turned off. But if I do this, I'm not sure what should happen if a user turns on the cameras for a system that is disarmed.

**Comment by bartdorsey** [comment]
1.0.3 is out, please update and see if this fixes this.

**Comment by lovie** [comment]
Yes it works
