### ISSUE TITLE
Causes Homebridge to become unresponsive to Home App 

### ISSUE THREAD

**Issue by gdotp01** [bartdorsey/homebridge-blinkcameras#24]
I've been having issues with Homebridge losing connection to the Home App ever since I updated my Blink Cameras to 2FA. See this issue https://github.com/homebridge/homebridge/issues/2585

After removing this plugin everything became stable again and its been working now for a week. What seems to happen is that if there are multiple calls to Blink to Arm/Disarm individual cameras (as there is an an automation where i only enable some at night if we are in) it almost immediately makes multiple accessories become unreachable in the Home App until i re-start the server. I can duplicate this by pressing multiple arms/disarms in the Home app for multiple camera quickly. If i do it more slowly waiting for each to return its status it appears top work.

**Comment by Venger2005** [comment]
> After removing this plugin everything became stable again and its been working now for a week. What seems to happen is that if there are multiple calls to Blink to Arm/Disarm individual cameras (as there is an an automation where i only enable some at night if we are in) it almost immediately makes multiple accessories become unreachable in the Home App until i re-start the server.

That was my experience as well - a routine I was using which called from multiple camera arms/disarms would lead to the same problem in the Home app.  Having removed the plug-in (as I’ve since removed my Blink cameras as I’ve replaced them), my Homebridge instance and Home app have now been stable for the last couple of days; with no further experiences of ‘no response‘ accessories.  So it was definitely this plug-in that was causing my Homebridge instance to become non-functional.

**Comment by lovie** [comment]
I have the same issue, after the 24 hour re-auth, the plugin freezes my home app too. I have added a fix by adding a method call “this.discover()” after the 24 hour reauth completes at line number 95 in index.js (getblink method). That fixed it for me.

**Comment by bartdorsey** [comment]
I've released version 1.1.0 of the plugin which should fix this issue. I've configured the plugin so every 24 hours it attempt to re-authenticate with the Blink API to get a new Token.
